### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: Retourneert het aantal qubits dat momenteel beschikbaar is voor gebruik.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Het aantal qubits dat in een `using`-instructie kan worden toegewezen.

      Als de gebruikte doel computer deze informatie niet verstrekt, wordt `-1` geretourneerd.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
ms.openlocfilehash: 1cb1331aa26ec9755a9e379336f46387b61bb0ae
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: nl-NL
ms.lasthandoff: 10/31/2019
ms.locfileid: "73230463"
