### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Samenvatting\n Deze functies bieden informatie over de omgeving waarin de Quantum berekening wordt uitgevoerd."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Retourneert het aantal qubits dat momenteel beschikbaar is om te lenen.

    Dit omvat niet-gebruikte qubits; dat wil zeggen dat de qubits die wordt geretourneerd `GetQubitsAvailableToUse`door.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Retourneert het aantal qubits dat momenteel beschikbaar is voor gebruik.
metadata:
  ms.openlocfilehash: bd6d442aabb179f4c5fea0a0f48efaa472ec00cf
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82673353"
