### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: microsoft.quantum.environment
summary: Retourneert het aantal qubits dat momenteel beschikbaar is voor gebruik.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Het aantal qubits dat in een instructie kan worden toegewezen `using` .

      Als de gebruikte doel computer deze informatie niet verstrekt, `-1` wordt deze geretourneerd.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 326195ba3fa7b880d9b6871d16ea7a12c1c9a2ea
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91484730"
