### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: Retourneert het aantal qubits dat momenteel beschikbaar is voor gebruik.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Het aantal qubits dat in een `using` instructie kan worden toegewezen.

      Als de gebruikte doel computer deze informatie niet verstrekt, `-1` wordt deze geretourneerd.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 82d8c27064cbb234b32707aa31fb0869f66ce23c
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682386"
