### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Retourneert het aantal qubits dat momenteel beschikbaar is om te lenen. Dit omvat niet-gebruikte qubits; dat wil zeggen dat de qubits die wordt geretourneerd door `GetQubitsAvailableToUse` .
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Retourneert het aantal qubits dat momenteel beschikbaar is voor gebruik.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Deze functies bieden informatie over de omgeving waarin de Quantum berekening wordt uitgevoerd.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 04a3ffe56be7da2c9adc13e2b27fe9ce0f982c44
  ms.sourcegitcommit: 29e0d88a30e4166fa580132124b0eb57e1f0e986
  ms.translationtype: MT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 10/27/2020
  ms.locfileid: "92702843"
