### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Retourneert het aantal qubits dat momenteel beschikbaar is om te lenen.

  Dit omvat niet-gebruikte qubits; dat wil zeggen de qubits die wordt geretourneerd door `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Het aantal qubits dat in een `borrowing`-instructie kan worden toegewezen.

      Als de gebruikte doel computer deze informatie niet verstrekt, wordt `-1` geretourneerd.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
ms.openlocfilehash: c0caf866ad9a8773aa11ee7c6951ca3acc60cbaa
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: nl-NL
ms.lasthandoff: 10/31/2019
ms.locfileid: "73230480"
