### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Retourneert het aantal qubits dat momenteel beschikbaar is om te lenen.

  Dit omvat niet-gebruikte qubits; dat wil zeggen dat de qubits die wordt geretourneerd `GetQubitsAvailableToUse`door.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Het aantal qubits dat in een `borrowing` instructie kan worden toegewezen.

      Als de gebruikte doel computer deze informatie niet verstrekt, `-1` wordt deze geretourneerd.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 99dd2afb66c334b112a2ee511b0437281da6b888
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682416"
