### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Retourneert het aantal qubits dat momenteel beschikbaar is om te lenen.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Retourneert het aantal qubits dat momenteel beschikbaar is voor gebruik.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Deze functies bieden informatie over de omgeving waarin de Quantum berekening wordt uitgevoerd.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201441"
